spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/rentcar
    username: postgres
    password: pass
    hikari:
      schema: ${car_rent.default-schema}
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  mvc:
     format:
       date: iso
       date-time: iso
       time: iso
  open-in-vew: false
server:
  ssl:
    enabled: false
logging:
  level:
    root: debug
car_rent:
  default-schema: car_rent
apache:
    catalina:
      core:
        AprLifecycleListener: off
app:
  image:
    bucket: /Users/natallia.vasilyeva/myProjects/car-rent/service/src/main/resources/static/images