spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/rentcar
    username: postgres
    password: pass
    hikari:
      schema: ${car_rent.default-schema}
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: update
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
database:
  defaultSchemaName: ${car_rent.default-schema}
logging:
  level:
    root: DEBUG
car_rent:
  default-schema: car_rent